Remove broken reference to the remote config in the bare example
The remote config was removed previously, because bazel can figure this out itself:
https://github.com/buildbarn/bb-deployments/commit/6bae7658de44b82bec2bc4d329351f15ced49f91

This fixes the following error:

ERROR: Config value remote is not defined in any .rc file