Use prebuilt protoc toolchain
This downloades a prebuilt protoc binary and uses that through regular
toolchain resolution (with the incompatible flag). This increases build
speed and removes the many compiler warnings that pop-up during
compilation of protoc sources. And more importantly works better on
Windows. Where for some reason the protoc compilation fails from an
external module:

    gits/bb-deployments $ bazel build \
        --override_module protobuf=../protobuf \
        @protobuf//src/google/protobuf:timestamp_proto
    ERROR: C:/tmp/eprbnvuo/external/protobuf~/src/google/protobuf/compiler/java/BUILD.bazel:99:11: Compiling src/google/protobuf/compiler/java/context.cc [for tool] failed: undeclared inclusion(s) in rule '@@protobuf~//src/google/protobuf/compiler/java:java':
    this rule is missing dependency declarations for the following files included by 'src/google/protobuf/compiler/java/context.cc':
      'bazel-out/x64_windows-opt-exec-ST-d57f47055a04/bin/external/protobuf~/src/google/protobuf/compiler/java/_virtual_includes/java/google/protobuf/compiler/java/context.h'

Whereas it does work when building from its own checkout:

    ~/gits/protobuf $ bazel build \
        //src/google/protobuf:timestamp_proto
    Target //src/google/protobuf:timestamp_proto up-to-date:
      bazel-bin/src/google/protobuf/timestamp_proto-descriptor-set.proto.bin
    INFO: Build completed successfully, 1 total action