Use the correct remote config name in the bare example
The example base .bazelrc config uses the name "rbe-ubuntu16-04" in
place of "remote" in the upstream bazelrc example, so we should refer
to that in the local config instead of "remote".

This fixes the following error:

ERROR: Config value remote is not defined in any .rc file